### ISSUE TITLE
Using IDOC for other example systems as shown in the paper

### ISSUE THREAD

**Issue by CheeGY** [mingu6/Implicit-Diff-Optimal-Control#1]
Hi! 

Thanks for releasing this repository! It's nice to have a accompanying repository while reading your paper, "Revisiting Implicit Differentiation for Learning Problems in Optimal Control", as it gives further details on the proposed methodology.

I have gone through the given example, CIOC_Cartpole_IDOC.py and I was wondering if you could release the other code to run the experiments for the other systems, _i.e._, 6-DoF Quadrotor, Robotarm and 6-DoF Rocket. In particular, I'm interested in re-creating some of the results for the other systems, as shown in Fig. 3 of your paper.

Thanks!

**Comment by mingu6** [comment]
Hi,

Thanks for taking interest in our work. I have put together the other examples and uploaded them to the repo for convenience. The modifications for our CIOC_{system_name}_IDOC.py compared to CIOC_{system_name}.py in the SafePDP repo are relatively straightforward and uniform across all systems.

**Comment by CheeGY** [comment]
Hi,

Thanks for uploading these examples. I'll take a look at them. Thanks again!
